@startuml
scale 2
package "navigation" #green{

package "nav_core" #Yellow{
abstract class BaseGlobalPlanner {
  +virtual bool makePlan () = 0
  +virtual bool  makePlan () = 0
  +virtual void  initialize () = 0
  +virtual  ~BaseGlobalPlanner () = 0
  #BaseGlobalPlanner ()
}

abstract class BaseLocalPlanner {
  +virtual bool computeVelocityCommands () = 0
  +virtual bool isGoalReached () = 0
  +virtual bool setPlan () = 0
  +virtual void initialize () = 0
  +virtual ~BaseLocalPlanner () 
  #BaseLocalPlanner ()
}

abstract class RecoveryBehavior {
  +virtual void initialize () = 0 
  +virtual void runBehavior () = 0 
  +virtual ~RecoveryBehavior () 
  #RecoveryBehavior ()
}
}


package "global planner" #YellowGreen{
  class AStarExpansion {}
    
  class DijkstraExpansion {}
    
  class Expander {}
    
  class GlobalPlanner {}
    
  class GradientPath {}
    
  class GridPath {}
    
  class Index {}
    
  class OrientationFilter {}
    
  class PlannerWithCostmap {}
    
  class PotentialCalculator {}
    
  class QuadraticCalculator {}
    
  class Traceback {}

  Expander <|-- AStarExpansion
  Expander <|-- DijkstraExpansion
  GlobalPlanner <|-- PlannerWithCostmap
  Traceback <|-- GradientPath
  Traceback <|-- GridPath
  PotentialCalculator <|-- QuadraticCalculator

}

package "carrot planner" #YellowGreen{
  class CarrotPlanner{}
}

package "navfn" #YellowGreen{
  class NavFn {}
  class NavfnROS {}
  class NavfnWithCostmap {}
  class NavWin {}
}

package "costmap_2d" #Pink{
  class Costmap2D {}
}

package "base_local_planner" #red {
  class TrajectoryPlannerROS {}
}

package "dwa_local_planner" #red {
  class DWAPlanner {}
	class DWAPlannerROS {}
}

BaseGlobalPlanner <|-- GlobalPlanner
BaseGlobalPlanner <|-- CarrotPlanner
BaseGlobalPlanner <|-- NavfnROS
NavfnROS <|-- NavfnWithCostmap
BaseLocalPlanner <|-- TrajectoryPlannerROS
BaseLocalPlanner <|-- DWAPlannerROS

}

@enduml